//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PyCloud.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppMenu
    {
        public int MenuId { get; set; }
        public string MeneType { get; set; }
        public int ParentMenuId { get; set; }
        public string MenuText { get; set; }
        public string MenuLink { get; set; }
        public string MenuSection { get; set; }
    }
}
